# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\ameen\Documents\softdump\cpp\sfml_projects\falling-sand

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\ameen\Documents\softdump\cpp\sfml_projects\falling-sand

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\ameen\Documents\softdump\cpp\sfml_projects\falling-sand\CMakeFiles C:\Users\ameen\Documents\softdump\cpp\sfml_projects\falling-sand\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\ameen\Documents\softdump\cpp\sfml_projects\falling-sand\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fallingsand

# Build rule for target.
fallingsand: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 fallingsand
.PHONY : fallingsand

# fast build rule for target.
fallingsand/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/build
.PHONY : fallingsand/fast

include/imgui-sfml/imgui-SFML.obj: include/imgui-sfml/imgui-SFML.cpp.obj
.PHONY : include/imgui-sfml/imgui-SFML.obj

# target to build an object file
include/imgui-sfml/imgui-SFML.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui-sfml/imgui-SFML.cpp.obj
.PHONY : include/imgui-sfml/imgui-SFML.cpp.obj

include/imgui-sfml/imgui-SFML.i: include/imgui-sfml/imgui-SFML.cpp.i
.PHONY : include/imgui-sfml/imgui-SFML.i

# target to preprocess a source file
include/imgui-sfml/imgui-SFML.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui-sfml/imgui-SFML.cpp.i
.PHONY : include/imgui-sfml/imgui-SFML.cpp.i

include/imgui-sfml/imgui-SFML.s: include/imgui-sfml/imgui-SFML.cpp.s
.PHONY : include/imgui-sfml/imgui-SFML.s

# target to generate assembly for a file
include/imgui-sfml/imgui-SFML.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui-sfml/imgui-SFML.cpp.s
.PHONY : include/imgui-sfml/imgui-SFML.cpp.s

include/imgui/backends/imgui_impl_opengl3.obj: include/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_opengl3.obj

# target to build an object file
include/imgui/backends/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.obj

include/imgui/backends/imgui_impl_opengl3.i: include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.i

include/imgui/backends/imgui_impl_opengl3.s: include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.s

include/imgui/backends/imgui_impl_win32.obj: include/imgui/backends/imgui_impl_win32.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_win32.obj

# target to build an object file
include/imgui/backends/imgui_impl_win32.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/backends/imgui_impl_win32.cpp.obj
.PHONY : include/imgui/backends/imgui_impl_win32.cpp.obj

include/imgui/backends/imgui_impl_win32.i: include/imgui/backends/imgui_impl_win32.cpp.i
.PHONY : include/imgui/backends/imgui_impl_win32.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_win32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/backends/imgui_impl_win32.cpp.i
.PHONY : include/imgui/backends/imgui_impl_win32.cpp.i

include/imgui/backends/imgui_impl_win32.s: include/imgui/backends/imgui_impl_win32.cpp.s
.PHONY : include/imgui/backends/imgui_impl_win32.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_win32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/backends/imgui_impl_win32.cpp.s
.PHONY : include/imgui/backends/imgui_impl_win32.cpp.s

include/imgui/imgui.obj: include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.obj

# target to build an object file
include/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.cpp.obj

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.obj: include/imgui/imgui_demo.cpp.obj
.PHONY : include/imgui/imgui_demo.obj

# target to build an object file
include/imgui/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_demo.cpp.obj
.PHONY : include/imgui/imgui_demo.cpp.obj

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.obj: include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.obj

# target to build an object file
include/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.cpp.obj

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_tables.obj: include/imgui/imgui_tables.cpp.obj
.PHONY : include/imgui/imgui_tables.obj

# target to build an object file
include/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_tables.cpp.obj
.PHONY : include/imgui/imgui_tables.cpp.obj

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.obj: include/imgui/imgui_widgets.cpp.obj
.PHONY : include/imgui/imgui_widgets.obj

# target to build an object file
include/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_widgets.cpp.obj
.PHONY : include/imgui/imgui_widgets.cpp.obj

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

include/src/particles.obj: include/src/particles.cpp.obj
.PHONY : include/src/particles.obj

# target to build an object file
include/src/particles.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/particles.cpp.obj
.PHONY : include/src/particles.cpp.obj

include/src/particles.i: include/src/particles.cpp.i
.PHONY : include/src/particles.i

# target to preprocess a source file
include/src/particles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/particles.cpp.i
.PHONY : include/src/particles.cpp.i

include/src/particles.s: include/src/particles.cpp.s
.PHONY : include/src/particles.s

# target to generate assembly for a file
include/src/particles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/particles.cpp.s
.PHONY : include/src/particles.cpp.s

include/src/quadtree.obj: include/src/quadtree.cpp.obj
.PHONY : include/src/quadtree.obj

# target to build an object file
include/src/quadtree.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/quadtree.cpp.obj
.PHONY : include/src/quadtree.cpp.obj

include/src/quadtree.i: include/src/quadtree.cpp.i
.PHONY : include/src/quadtree.i

# target to preprocess a source file
include/src/quadtree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/quadtree.cpp.i
.PHONY : include/src/quadtree.cpp.i

include/src/quadtree.s: include/src/quadtree.cpp.s
.PHONY : include/src/quadtree.s

# target to generate assembly for a file
include/src/quadtree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/quadtree.cpp.s
.PHONY : include/src/quadtree.cpp.s

include/src/thread_pool.obj: include/src/thread_pool.cpp.obj
.PHONY : include/src/thread_pool.obj

# target to build an object file
include/src/thread_pool.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/thread_pool.cpp.obj
.PHONY : include/src/thread_pool.cpp.obj

include/src/thread_pool.i: include/src/thread_pool.cpp.i
.PHONY : include/src/thread_pool.i

# target to preprocess a source file
include/src/thread_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/thread_pool.cpp.i
.PHONY : include/src/thread_pool.cpp.i

include/src/thread_pool.s: include/src/thread_pool.cpp.s
.PHONY : include/src/thread_pool.s

# target to generate assembly for a file
include/src/thread_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/include/src/thread_pool.cpp.s
.PHONY : include/src/thread_pool.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\fallingsand.dir\build.make CMakeFiles/fallingsand.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... fallingsand
	@echo ... include/imgui-sfml/imgui-SFML.obj
	@echo ... include/imgui-sfml/imgui-SFML.i
	@echo ... include/imgui-sfml/imgui-SFML.s
	@echo ... include/imgui/backends/imgui_impl_opengl3.obj
	@echo ... include/imgui/backends/imgui_impl_opengl3.i
	@echo ... include/imgui/backends/imgui_impl_opengl3.s
	@echo ... include/imgui/backends/imgui_impl_win32.obj
	@echo ... include/imgui/backends/imgui_impl_win32.i
	@echo ... include/imgui/backends/imgui_impl_win32.s
	@echo ... include/imgui/imgui.obj
	@echo ... include/imgui/imgui.i
	@echo ... include/imgui/imgui.s
	@echo ... include/imgui/imgui_demo.obj
	@echo ... include/imgui/imgui_demo.i
	@echo ... include/imgui/imgui_demo.s
	@echo ... include/imgui/imgui_draw.obj
	@echo ... include/imgui/imgui_draw.i
	@echo ... include/imgui/imgui_draw.s
	@echo ... include/imgui/imgui_tables.obj
	@echo ... include/imgui/imgui_tables.i
	@echo ... include/imgui/imgui_tables.s
	@echo ... include/imgui/imgui_widgets.obj
	@echo ... include/imgui/imgui_widgets.i
	@echo ... include/imgui/imgui_widgets.s
	@echo ... include/src/particles.obj
	@echo ... include/src/particles.i
	@echo ... include/src/particles.s
	@echo ... include/src/quadtree.obj
	@echo ... include/src/quadtree.i
	@echo ... include/src/quadtree.s
	@echo ... include/src/thread_pool.obj
	@echo ... include/src/thread_pool.i
	@echo ... include/src/thread_pool.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

